steps:
  - name: gcr.io/cloud-builders/npm
    args:
      - install
    dir: ./
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - CatUsCloudFunction
      - '--trigger-http'
      - '--runtime'
      - nodejs14
      - '--entry-point'
      - catusService
      - '--region'
      - asia-southeast1
    dir: ./

#gcloud functions deploy CatUsCloudFunction --allow-unauthenticated --runtime nodejs14 --trigger-http --entry-point catusService
